name: Selenium Tests and Unit Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Installing all necessary packages
      run: |
        pip install chromedriver-autoinstaller selenium pyvirtualdisplay
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          sudo apt-get install xvfb
        fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Flask Application
      run: |
        python main.py &

    - name: Wait for Flask to start
      run: sleep 10

    - name: Run Tests
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          python tests/selenium_tests_windows.py
          python tests/unit_tests.py
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          python tests/selenium.py
          python tests/unit_tests.py
        else
          python tests/selenium_tests.py
          python tests/unit_tests.py
        fi
